image:
  file: .gitpod.Dockerfile

ports:
  - port: 1337
    visibility: public
  - port: 3000
    visibility: public

tasks:
  - name: "database"
    command: docker-compose up
  - name: "backend"
    command: cd backend && npm i
  - name: "frontend"
    command: cd frontend && npm i

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - dsznajder.es7-react-js-snippets
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - eamodio.gitlens
    - bierner.jsdoc-markdown-highlighting
    - esbenp.prettier-vscode
    - chakrounanas.turbo-console-log
    - hbenl.vscode-test-explorer
