---
- name: Add service cert to traefik.yml
  hosts: all
  become: yes
  vars:
    - service_url: "{{ SERVICE_URL }}"
  tasks:
    - name: Copy yaml_editor.py
      copy:
        src: ../traefik/yaml_editor.py
        dest: /home/code/yaml_editor.py

    - name: Add service cert to traefik.yml
      shell:
        cmd: "python3 /home/code/yaml_editor.py {{ service_url }}"

    - name: Trigger updates in Traefik
      retries: 5
      delay: 5
      # until: >
      #   update_service.stdout_lines.find("Service converged") != -1
      shell:
        cmd: "docker service update traefik_traefik --force"
      register: update_service

    # - name: debug
    #   debug:
    #     var: update_service

    - name: Delete artifact files
      file:
        path: "/home/code/{{ item }}"
        state: absent
      loop:
        - "yaml_editor.py"
