version: "3.7"

services:
  sps_frontend:
    image: registry.hub.docker.com/your_dockerhub_username/sps_frontend:0.0.1
    networks:
      - traefik_default
    environment:
      NODE_ENV: production
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.services.sps_frontend.loadbalancer.server.port=3000
        - traefik.http.routers.sps_frontend.entrypoints=websecure
        - traefik.http.routers.sps_frontend.tls=true
        - traefik.http.routers.sps_frontend.rule=Host(`yourstartup.com`)
        - traefik.docker.network=traefik_default

networks:
  traefik_default:
    external: true
