version: "3.7"

services:
  sps_backend:
    image: singlepagestartup/sps_lite_backend
    # image: registry.hub.docker.com/your_dockerhub_username/sps_backend:0.0.1
    networks:
      - traefik_overlay
    volumes:
      - ./sps_backend_uploads:/usr/src/app/public/uploads
    env_file:
      - ./sps-lite.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1337
      - SEED_ENTITES=true
      - DATABASE_HOST=<your_database_host>
      - DATABASE_CLIENT=postgres
      - DATABASE_PORT=<your_database_port>
      - DATABASE_NAME=<your_database_name>
      - DATABASE_USERNAME=<your_database_username>
      - SET_PERMISSIONS=true
      # if you are using Amazon SES
      - EMAIL_PROVIDER=amazon-ses
      - AWS_SES_URL=<your_aws_ses_url>
      - AWS_SES_DEFAULT_FROM=<your_no_reply_email_address>
      - AWS_SES_DEFAULT_REPLY_TO=<your_email_address>
      # if you are using Amazon S3
      - AWS_S3_ACCESS_KEY_ID=<your_aws_access_key_id>
      - AWS_S3_BUCKET=<your_aws_s3_bucket>
      - AWS_S3_ENDPOINT=<your_aws_s3_endpoint>
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.services.sps_backend.loadbalancer.server.port=1337
        - traefik.http.routers.sps_backend.entrypoints=websecure
        - traefik.http.routers.sps_backend.tls=true
        - traefik.http.routers.sps_backend.rule=Host(`api.yourstartup.com`)
        - traefik.docker.network=traefik_overlay

networks:
  traefik_overlay:
    external: true
