---
- name: Install Node.js
  hosts: all
  become: true
  tasks:
    - name: Install Node.js
      shell: |
        curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs
