- name: Update packages
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: false
        cache_valid_time: 3600
      register: apt_res
      retries: 5
      until: apt_res | success
