version: "3.7"

services:
  db:
    extends:
      file: ./docker-compose.postgres.yaml
      service: postgres
    networks:
      - sps_db_network

  adminer:
    extends:
      file: ./docker-compose.adminer.yaml
      service: adminer
    networks:
      - sps_db_network

networks:
  sps_db_network:
    external: false
    name: sps_db_network
