---
- name: Add private DockerHub registry
  hosts: all
  become: yes
  vars:
    - domain: "{{ DOMAIN }}"
    - portainer_username: "{{ PORTAINER_USERNAME }}"
    - portainer_password: "{{ PORTAINER_PASSWORD }}"
    - docker_hub_username: "{{ DOCKER_HUB_USERNAME }}"
    - docker_hub_password: "{{ DOCKER_HUB_PASSWORD }}"
    - docker_hub_url: "{{ DOCKER_HUB_URL }}"
    - docker_hub_login_username: "{{ DOCKER_HUB_LOGIN_USERNAME }}"
    - portainer_url: "{{ PORTAINER_URL }}"
  tasks:
    - name: Login to Portainer
      uri:
        url: "https://{{ portainer_url }}/api/auth"
        method: POST
        body_format: json
        body:
          username: "{{ portainer_username }}"
          password: "{{ portainer_password }}"
      register: portainer_login

    - name: Add DockerHub registry
      uri:
        url: "https://{{ portainer_url }}/api/registries"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ portainer_login.json.jwt }}"
        body:
          Name: "dockerhub-{{ docker_hub_login_username }}"
          Type: 3
          URL: "{{ docker_hub_url }}"
          Authentication: true
          Username: "{{ docker_hub_login_username }}"
          Password: "{{ docker_hub_password }}"
      register: docker_hub_registry
      ignore_errors: yes

    - name: Save DockerHub registry id
      copy:
        content: "{{ docker_hub_registry.json.Id }}"
        dest: /home/code/docker_hub_registry_id
      when: docker_hub_registry.json.Id is defined
