---
- name: Create Traefik
  hosts: all
  become: yes
  tasks:
    - name: Get ansible ansible_system_vendor
      set_fact:
        ansible_system_vendor: "{{ hostvars[inventory_hostname]['ansible_system_vendor'] }}"

    - name: Copy traefik.yml file
      ansible.builtin.template:
        src: traefik.yml.j2
        dest: /home/code/traefik.yml

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.traefik.yaml.j2
        dest: /home/code/docker-compose.traefik.yaml

    - name: If DigitalOcean
      block:
        - name: Install jsondiff Python package
          pip:
            name: jsondiff
            executable: pip3
            extra_args: --no-build-isolation --break-system-packages
      when: ansible_system_vendor == "DigitalOcean"

    - name: If not DigitalOcean
      block:
        - name: Install jsondiff Python package
          pip:
            name: jsondiff
            executable: pip3
            extra_args: --no-build-isolation
      when: ansible_system_vendor != "DigitalOcean"

    - name: Run Traefik service
      community.docker.docker_stack:
        state: present
        name: traefik
        compose:
          - /home/code/docker-compose.traefik.yaml
