---
- name: Create Portainer user and add private DockerHub registry
  hosts: all
  become: yes
  vars:
    - domain: "{{ DOMAIN }}"
    - portainer_username: "{{ PORTAINER_USERNAME }}"
    - portainer_password: "{{ PORTAINER_PASSWORD }}"
    - docker_hub_username: "{{ DOCKER_HUB_USERNAME }}"
    - docker_hub_password: "{{ DOCKER_HUB_PASSWORD }}"
    - docker_hub_url: "{{ DOCKER_HUB_URL }}"
    - docker_hub_login_username: "{{ DOCKER_HUB_LOGIN_USERNAME }}"
    - portainer_url: "{{ PORTAINER_URL }}"
  tasks:
    - name: Create Portainer user request
      ignore_errors: yes
      retries: 3
      delay: 3
      uri:
        url: "https://{{ portainer_url }}/api/users/admin/init"
        method: POST
        body: "{{ lookup('template','create_portainer_user_body.json.j2') | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"
