---
- name: Delete Sentry Projects
  hosts: all
  become: yes
  vars:
    sentry_root_api_key: "{{ SENTRY_ROOT_API_KEY }}"
    sentry_root_organization_slug: "{{ SENTRY_ROOT_ORGANIZATION_SLUG }}"
    sentry_root_team_slug: "{{ SENTRY_ROOT_TEAM_SLUG }}"
    project_name: "{{ PROJECT_NAME }}"
  tasks:
    - name: Delete sentry projects
      uri:
        url: "https://sentry.io/api/0/projects/{{ sentry_root_organization_slug }}/{{ project_name }}_{{ item }}/"
        method: DELETE
        headers:
          Authorization: "Bearer {{ sentry_root_api_key }}"
        status_code: 204
      register: sentry_project
      ignore_errors: yes
      loop:
        - "frontend"
        - "backend"

    - name: Delete files with DSN keys
      file:
        path: "/home/code/{{ item }}_sentry_dsn.env"
        state: absent
      loop:
        - "frontend"
        - "backend"
