---
- name: Delete S3 bucket
  hosts: all
  become: yes
  vars:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_access_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    project_name: "{{ PROJECT_NAME }}"
  tasks:
    - name: Install required Python packages
      pip:
        name: "{{ item }}"
        state: present
        executable: pip3
        extra_args: --no-build-isolation
      loop:
        - boto
        - boto3
        - botocore
        - awscli

    - name: Delete S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ project_name }}"
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_access_key }}"
        state: absent
        force: true
      ignore_errors: yes
