---
- name: Delete ansible secrets from GitHub
  hosts: all
  become: yes
  vars:
    - github_token: "{{ GITHUB_TOKEN }}"
    - github_repository: "{{ GITHUB_REPOSITORY }}"
  tasks:
    - name: Delete secrets from GitHub
      shell:
        cmd: "gh secret delete {{ item }} --repo {{ github_repository }}"
      loop:
        - ANSIBLE_HOST
        - ANSIBLE_PASSWORD
        - ANSIBLE_ENV_BASE64
        - CLOUDFLARE_ACCOUNT_API_KEY
        - ROOT_AWS_ACCESS_KEY
        - ROOT_AWS_SECRET_ACCESS_KEY
        - TRAEFIK_PASSWORD
        - PORTAINER_PASSWORD
        - POSTGRES_PASSWORD
        - CLOUDFLARE_ACCOUNT_EMAIL
        - GH_TOKEN
      ignore_errors: yes

    - name: Delete gh_token.txt file
      file:
        path: /home/code/gh_token.txt
        state: absent
