- name: Install Node.js
  hosts: all
  become: yes
  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        # update_cache: yes
        cache_valid_time: 3600

    - name: Install npm
      apt:
        name: npm
        state: present
        # update_cache: yes
        cache_valid_time: 3600

    - name: Check version
      shell: nodejs --version
      register: nodejs_version

    - debug:
        msg: "{{ nodejs_version.stdout }}"
