- name: Set cron jobs
  hosts: all
  become: yes
  tasks:
    - name: docker image prune cron
      cron:
        name: "docker image prune"
        minute: "20,40"
        hour: "*"
        job: "yes | docker image prune  >> /home/code/docker_image_prune.log"

    - name: docker container prune cron
      cron:
        name: "docker container prune"
        minute: "0"
        hour: "*"
        job: "yes | docker container prune  >> /home/code/docker_container_prune.log"
