name: Update backend

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string

env:
  BACKEND_IMAGE_URL: ${{ secrets.DOCKER_HUB_URL }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.PROJECT_NAME }}_backend:${{ inputs.TAG }}

jobs:
  create-backend-image:
    if: ${{ inputs.ENVIRONMENT == 'staging' }}
    name: Backend version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_HUB_URL }}
          username: ${{ secrets.DOCKER_HUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          logout: false
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: false
          load: true
          tags: ${{ env.BACKEND_IMAGE_URL }}
      - name: Inspect image
        run: docker image inspect ${{ env.BACKEND_IMAGE_URL }}
      - name: Push to registry
        run: docker push ${{ env.BACKEND_IMAGE_URL }}

  deploy-backend:
    name: Run deployer
    runs-on: ubuntu-latest
    needs:
      - create-backend-image
    steps:
      - name: Send webhook for staging service update
        if: ${{ inputs.ENVIRONMENT == 'staging' }}
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.PORTAINER_STAGING_BACKEND_UPDATE_URL }}?tag=${{ inputs.TAG }}
          method: "POST"
          timeout: 40000
      - name: Send webhook for production service update
        if: ${{ inputs.ENVIRONMENT == 'production' }}
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.PORTAINER_PRODUCTION_BACKEND_UPDATE_URL }}?tag=${{ inputs.TAG }}
          method: "POST"
          timeout: 40000
