name: Create ansible env

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-ansible-env:
    name: Create ansible env
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/ansible
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create inventory file
        run: |
          cp gh_actions_inventory.yaml inventory.yaml
      - name: Check inventory file
        run: cat inventory.yaml
      - name: Check inventory.yaml
        run: cat inventory.yaml
      - name: Create .env file
        run: |
          echo "${{ secrets.ANSIBLE_ENV_BASE64 }}" | base64 -d > .env
      - name: Replace ANSIBLE_HOST in inventory.yaml
        run: |
          sed -ie "s/ANSIBLE_HOST/${{ secrets.ANSIBLE_HOST }}/g" inventory.yaml
      - name: Replace ANSIBLE_PASSWORD in inventory.yaml
        run: |
          sed -ie "s/ANSIBLE_PASSWORD/${{ secrets.ANSIBLE_PASSWORD }}/g" inventory.yaml
      - name: Add CLOUDFLARE_ACCOUNT_EMAIL to env file
        run: |
          echo -e "\nCLOUDFLARE_ACCOUNT_API_KEY=${{ secrets.CLOUDFLARE_ACCOUNT_API_KEY }}" >> .env
          echo -e "\nSENTRY_ROOT_API_KEY=${{ secrets.SENTRY_ROOT_API_KEY }}" >> .env
          echo -e "\nSENTRY_ROOT_ORGANIZATION_SLUG=${{ secrets.SENTRY_ROOT_ORGANIZATION_SLUG }}" >> .env
          echo -e "\nSENTRY_ROOT_TEAM_SLUG=${{ secrets.SENTRY_ROOT_TEAM_SLUG }}" >> .env
          echo -e "\nROOT_AWS_SECRET_ACCESS_KEY=${{ secrets.ROOT_AWS_SECRET_ACCESS_KEY }}" >> .env
          echo -e "\nDOCKER_HUB_PASSWORD=${{ secrets.DOCKER_HUB_PASSWORD }}" >> .env
          echo -e "\nGITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> .env
          echo -e "\nTRAEFIK_PASSWORD=${{ secrets.TRAEFIK_PASSWORD }}" >> .env
          echo -e "\nPORTAINER_PASSWORD=${{ secrets.PORTAINER_PASSWORD }}" >> .env
          echo -e "\nPOSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo -e "\nJWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo -e "\nADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" >> .env
          echo -e "\nAPP_KEYS=${{ secrets.APP_KEYS }}" >> .env
          echo -e "\nAPI_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}" >> .env
      - name: Check .env file
        run: cat .env
