name: Deploy backend

on:
  pull_request:
    types: [closed]
    branches:
      - deploy-backend

jobs:
  update-backend:
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      TAG: ${{ github.sha }}
      ENVIRONMENT: "staging"
