name: Deploy project to internetcomputer
on:
  push:
    branches:
      - deploy
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - deploy

jobs:
  build-frontend-with-backend-data:
    timeout-minutes: 20
    name: Run ansible playbook
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/ansible
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # - name: Check md5
      #   run: echo -n fit | md5sum | awk '{print $1}'
      - name: Create inventory file
        run: |
          echo "${{ secrets.INVENTORY_BASE64 }}" | base64 -d > inventory.yaml
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_BASE64 }}" | base64 -d > .env
      # - name: List directory
      #   run: ls -la
      - name: Add CLOUDFLARE_ACCOUNT_EMAIL to env file
        run: |
          echo -e "\CLOUDFLARE_ACCOUNT_EMAIL=${{ vars.CLOUDFLARE_ACCOUNT_EMAIL }}" >> .env
      - name: Add CLOUDFLARE_ACCOUNT_API_KEY to env file
        run: |
          echo -e "\CLOUDFLARE_ACCOUNT_API_KEY=${{ secrets.CLOUDFLARE_ACCOUNT_API_KEY }}" >> .env
      - name: Add ROOT_AWS_ACCESS_KEY to env file
        run: |
          echo -e "\ROOT_AWS_ACCESS_KEY=${{ secrets.ROOT_AWS_ACCESS_KEY }}" >> .env
      - name: Add ROOT_AWS_SECRET_ACCESS_KEY to env file
        run: |
          echo -e "\ROOT_AWS_SECRET_ACCESS_KEY=${{ secrets.ROOT_AWS_SECRET_ACCESS_KEY }}" >> .env
      - name: Add DOCKER_HUB_PASSWORD to env file
        run: |
          echo -e "\DOCKER_HUB_PASSWORD=${{ secrets.DOCKER_HUB_PASSWORD }}" >> .env
      - name: Add GITHUB_TOKEN to env file
        run: |
          echo -e "\GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> .env
      - name: Check .env file
        run: cat .env
      # - name: Make scripts files executable
      #   run: |
      #     cd ./deployment/ansible && \
      #     chmod +x \
      #     ./server.sh
      # - name: Run scripts
      #   run: |
      #     cd ./deployment/ansible && \
      #     ./server.sh