name: Deploy project to internetcomputer
on:
  push:
    branches:
      - deploy
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - deploy
jobs:
  build-frontend-with-backend-data:
    timeout-minutes: 5
    name: Run ansible playbook
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Go to ansible directory
        run: cd deployment/ansible
      - name: Create inventory file
        run: |
          echo "${{ vars.INVENTORY_BASE64 }}" | base64 -d > inventory.yaml
      - name: Get inventory file
        run: cat inventory.yaml
      - name: List directory
        run: ls -la
      - name: Make scripts files executable
        run: |
          chmod +x ./server.sh
      - name: Run scripts
        run: ./server.sh