name: Deploy project
on:
  push:
    branches:
      - main
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - deploy

jobs:
  build-frontend-with-backend-data:
    timeout-minutes: 25
    name: Run backend and frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      # - name: Run backend
      #   env:
      #     AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
      #     AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT }}
      #     AWS_S3_REGION: ${{ vars.AWS_S3_REGION }}
      #     AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      #     AWS_S3_ACCESS_SECRET: ${{ secrets.AWS_S3_ACCESS_SECRET }}
      #   run: |
      #     cd backend
      #     npm i
      #     npm run build
      #     cp .env.deployer .env
      #     npm run start &
      - name: Make scripts files executable
        run: |
          chmod +x \
          ./wait-for-seeed.sh \
          ./frontend/icp-pass-envs-to-files.sh \
          ./frontend/icp-import-identity.sh \
          ./frontend/icp-update-canister.sh
      - name: Run frontend
        env:
          ICP_DEPLOYER_WALLET: ${{ vars.ICP_DEPLOYER_WALLET }}
          ICP_DEPLOYER_KEY: ${{ secrets.ICP_DEPLOYER_KEY }}
        run: |
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
          cd frontend
          ./icp-pass-envs-to-files.sh
          ./icp-import-identity.sh
      #     npm i
      #     rm -rf .env.production
      #     cp .env.development .env.production
      #     ./icp-update-canister.sh
