name: Deploy project to server

on:
  pull_request:
    types: [closed]
    branches:
      - deploy

jobs:
  create-ansible-env:
    uses: ./.github/workflows/create-ansible-env.yml
    secrets: inherit

  deploy-project-to-server:
    timeout-minutes: 60
    name: Run ansible playbook
    runs-on: ubuntu-latest
    needs:
      - create-ansible-env
    defaults:
      run:
        working-directory: ./deployment/ansible
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check .env file
        run: cat .env
      - name: Make scripts files executable
        run: |
          chmod +x \
          ./server.sh \
          ./aws.sh \
          ./sentry.sh \
          ./cloudflare.sh \
          ./services.sh \
          ./github.sh
      - name: Run server.sh
        run: |
          ./server.sh up
      # - name: Run aws.sh
      #   run: |
      #     ./aws.sh up
      # - name: Run sentry.sh
      #   run: |
      #     ./sentry.sh up
      # - name: Run cloudflare.sh
      #   run: |
      #     ./cloudflare.sh up
      # - name: Run services.sh
      #   run: |
      #     ./services.sh up
      # - name: Run github.sh
      #   run: |
      #     ./github.sh up
