name: Deploy project to internetcomputer
on:
  push:
    branches:
      - deploy
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - deploy
jobs:
  build-frontend-with-backend-data:
    timeout-minutes: 5
    name: Run ansible playbook
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Go to ansible directory
        run: cd ./deployment/ansible
      - name: Create inventory file
        run: |
          echo "${{ vars.INVENTORY_BASE64 }}" | base64 -d > ./deployment/ansible/inventory.yaml
      - name: Make scripts files executable
        run: |
          cd ./deployment/ansible && \
          chmod +x \
          ./server.sh
      - name: Run scripts
        run: |
          cd ./deployment/ansible && \
          ./server.sh