name: Deploy project
on:
  push:
    branches:
      - main
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - deploy

jobs:
  build-frontend-with-backend-data:
    timeout-minutes: 25
    name: Run backend and frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check envs
        run: env
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT }}
          AWS_S3_REGION: ${{ vars.AWS_S3_REGION }}
      # - name: Run backend
      #   run: |
      #     cd backend
      #     npm i
      #     npm run build
      #     cp .env.deployer .env
      #     npm run start &
      # - name: Make the script files executable
      #   run: chmod +x wait-for-seeed.sh
      # - name: Run frontend
      #   run: |
      #     ./wait-for-seeed.sh
      #     cd frontend
      #     npm i
      #     rm -rf .env.production
      #     cp .env.development .env.production
      #     npm run build
