name: Deploy documentation
on:
  pull_request:
    types: [closed]
    branches:
      - documentation

env:
  DOCUMENTATION_IMAGE_URL: ${{ vars.DOCKER_HUB_URL }}/${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.PROJECT_NAME }}_documentation:latest

jobs:
  create-documentation-image:
    name: Documentation version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.DOCKER_HUB_URL }}
          username: ${{ vars.DOCKER_HUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          logout: false
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./documentation
          push: false
          load: true
          tags: ${{ env.DOCUMENTATION_IMAGE_URL }}
      - name: Inspect image
        run: docker image inspect ${{ env.DOCUMENTATION_IMAGE_URL }}
      - name: Push to registry
        run: docker push ${{ env.DOCUMENTATION_IMAGE_URL }}

  deploy-documentation:
    name: Run deployer
    runs-on: ubuntu-latest
    needs:
      - create-documentation-image
    steps:
      - name: Send webhook for service update
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.PORTAINER_STAGING_DOCUMENTATION_UPDATE_URL }}?tag=latest
          method: "POST"
