name: Seed database
on:
  pull_request:
    types: [closed]
    branches:
      - seed-database

jobs:
  fill-database-with-seed-data:
    timeout-minutes: 25
    name: Seed backend data
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run backend
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT }}
          AWS_S3_REGION: ${{ vars.AWS_S3_REGION }}
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_ACCESS_SECRET: ${{ secrets.AWS_S3_ACCESS_SECRET }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ vars.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_SSL: ${{ vars.DATABASE_SSL == true }}
          DATABASE_SSL_SELF_SIGNED: ${{ vars.DATABASE_SSL_SELF_SIGNED == true }}
        run: |
          cd backend
          npm i
          npm run build
          cp .env.seed .env
          npm run start &
      - name: Make scripts files executable
        run: |
          chmod +x ./wait-for-seeed.sh
      - name: Wait until seed is finished
        run: |
          ./wait-for-seeed.sh
