name: Create prerelease version deployment
on:
  release:
    types:
      - published
      - released

env:
  FRONTEND_IMAGE_URL: ${{ vars.DOCKER_HUB_URL }}/${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.PROJECT_NAME }}_frontend:${{ github.event.release.tag_name }}
  BACKEND_IMAGE_URL: ${{ vars.DOCKER_HUB_URL }}/${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.PROJECT_NAME }}_backend:${{ github.event.release.tag_name }}
  NEXT_PUBLIC_BACKEND_URL: ${{ vars.NEXT_PUBLIC_BACKEND_URL }}
  NEXT_PUBLIC_BACKEND_TOKEN: ${{ secrets.NEXT_PUBLIC_BACKEND_TOKEN }}
  NEXT_PUBLIC_FRONTEND_URL: ${{ vars.NEXT_PUBLIC_FRONTEND_URL }}

jobs:
  create-backend-image:
    if: ${{ github.event.release.prerelease == true }}
    name: Backend version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.DOCKER_HUB_URL }}
          username: ${{ vars.DOCKER_HUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          logout: false
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: false
          load: true
          tags: ${{ env.BACKEND_IMAGE_URL }}
      - name: Inspect image
        run: docker image inspect ${{ env.BACKEND_IMAGE_URL }}
      - name: Push to registry
        run: docker push ${{ env.BACKEND_IMAGE_URL }}

  deploy-backend:
    if: ${{ github.event.release.prerelease == true }}
    name: Run deployer
    runs-on: ubuntu-latest
    needs:
      - create-backend-image
    steps:
      - name: Send webhook for service update
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ vars.PORTAINER_STAGING_BACKEND_UPDATE_URL }}?tag=${{ github.event.release.tag_name }}
          method: "POST"

  create-frontend-image:
    name: Frontend version
    runs-on: ubuntu-latest
    needs:
      - create-backend-image
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Sleep until backend starts
        run: sleep 360
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.DOCKER_HUB_URL }}
          username: ${{ vars.DOCKER_HUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          logout: false
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: false
          load: true
          tags: ${{ env.FRONTEND_IMAGE_URL }}
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ env.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_PUBLIC_BACKEND_TOKEN=${{ env.NEXT_PUBLIC_BACKEND_TOKEN }}
            NEXT_PUBLIC_FRONTEND_URL=${{ env.NEXT_PUBLIC_FRONTEND_URL }}
      - name: Inspect image
        run: docker image inspect ${{ env.FRONTEND_IMAGE_URL }}
      - name: Push to registry
        run: docker push ${{ env.FRONTEND_IMAGE_URL }}

  deploy-frontend:
    name: Run deployer
    runs-on: ubuntu-latest
    needs:
      - create-frontend-image
    steps:
      - name: Send webhook for service update
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ vars.PORTAINER_STAGING_FRONTEND_UPDATE_URL }}?tag=${{ github.event.release.tag_name }}
          method: "POST"