name: Create prerelease version deployment

on:
  release:
    types:
      - published
      - released

env:
  BACKEND_IMAGE_URL: ${{ secrets.DOCKER_HUB_URL }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.PROJECT_NAME }}_backend:${{ github.event.release.tag_name }}

jobs:
  update-backend:
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      TAG: ${{ github.event.release.tag_name }}
      ENVIRONMENT: "staging"

  fill-database-with-seed-data:
    uses: ./.github/workflows/database.yml
    secrets: inherit
    needs:
      - update-backend

  update-frontend:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    needs:
      - fill-database-with-seed-data
    with:
      SLEEP_TIME: 360
      TAG: ${{ github.event.release.tag_name }}
      ENVIRONMENT: "staging"
